package com.redhat;

import com.redhat.Business;
import com.redhat.RuleResponse;
import com.redhat.Reason;
import java.util.ArrayList;

rule "filter out Kansas"
ruleflow-group "filter"
dialect "mvel"

	when
		$business : Business( stateCode == "KS" )
	then
		insert ( new String( "filtered" ) );
		Reason reason = new Reason();
		reason.setReasonMessage( "business filtered from Kansas not found" );
		insert ( reason );
end